baseURL = 'https://incluyo.lgbt'
languageCode = 'es-mx'

title = 'Incluyo'
theme = 'incluyo2.0'

[params]
  description = 'Incluyo LGBT es un emprendimiento social que fomenta el desarrollo emocional y personal de juventudes LGBTQ+.'
  author = 'Incluyo LGBT'
  keywords = 'incluyo,lgbt,lgbtq,lgbtq+,gay,lesbiana,bi,bisexual,homosexual,trans,transgenero,transexual,trabesti,homosexual,apoyo,jovenes,juventud,intersexual,asexual,pansexual,familia,queer,pride,orgullo'

  contentfulContentURL = "https://cdn.contentful.com/spaces/5gmwaxnst2mo/environments/master/entries?"
  contentfulAssetsURL = "https://cdn.contentful.com/spaces/5gmwaxnst2mo/environments/master/assets/"
  contentfulAPIKey = "U2D7ENiC4tzF4fbG3CAXWsNcl6G-rvJMG1BSCRmLZZ8"

  enforceSSL = true

[menu]
  [[menu.main]]
    name = "Inicio"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Conócenos"
    identifier = "conocenos"
    url = "/conocenos"
    weight = 2
  [[menu.main]]
    name = "Metodología"
    identifier = "metodologia"
    url = "/metodologia"
    weight = 3
  [[menu.main]]
    name = "Contacto"
    identifier = "contacto"
    url = "/contacto"
    weight = 5

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    
